name: MinecraftCurrencyPlugin
main: com.example.myplugin.MinecraftCurrencyPlugin
version: 1.0.0
api-version: 1.21.3
description: A Minecraft plugin for currency and villager shops.
commands:
  createshop:
    description: Create a villager shop.
    usage: /createshop <shopName>
  removeshop:
    description: Remove a villager shop.
    usage: /removeshop <shopName>
  pay:
    description: Transfer money to another player.
    usage: /pay <player> <amount>
  balance:
    description: Check your current balance.
    usage: /balance
  setstartingcapital:
    description: Set starting capital for all players.
    usage: /setstartingcapital <amount>
